name: Testing Secret Variables

on:
  workflow_dispatch

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.MY_KEY }}"
          ${{ secrets.MY_KEY }}